#!/bin/bash

# Get super user privileges
if [[ $EUID != 0 ]]; then
    sudo "$0" "$@"
    exit $?
fi

echo 'deb http://www.rabbitmq.com/debian/ testing main' | tee /etc/apt/sources.list.d/rabbitmq.list
wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | apt-key add -
apt-get update
apt-get install rabbitmq-server avahi-daemon avahi-discover avahi-utils -y

rabbitmqctl delete_user guest

rabbitmqctl add_user admin admin
rabbitmqctl set_user_tags admin administrator

rabbitmqctl add_user ispace ispace

rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
rabbitmqctl set_permissions -p / ispace ".*" ".*" ".*"

rabbitmq-plugins enable rabbitmq_management

cp rabbitmq.service /etc/avahi/services/rabbitmq.service

printf '[x] Done...\n[x] Management plugin running at http://localhost:15672\n\n'   
