#!/bin/bash

# Get super user privileges
if [[ $EUID != 0 ]]; then
    sudo "$0" "$@"
    exit $?
fi

echo 'deb http://www.rabbitmq.com/debian/ testing main' | tee /etc/apt/sources.list.d/rabbitmq.list
wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | apt-key add -
apt-get update
apt-get install rabbitmq-server

rabbitmqctl delete_user guest
rabbitmqctl delete_vhost /

rabbitmqctl add_user admin admin
rabbitmqctl set_user_tags admin administrator

rabbitmqctl add_user ispace ispace

rabbitmqctl add_vhost is
rabbitmqctl set_permissions -p is admin ".*" ".*" ".*"
rabbitmqctl set_permissions -p is ispace ".*" ".*" ".*"
